version = 3.9.4
runner.dialect = scala3
maxColumn = 100
align.preset = more
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = yes
rewrite.scala3.insertEndMarkerMinLines = 40
newlines.source = keep
docstrings.style = SpaceAsterisk
project.excludePaths = ["glob:**/vendor/**"]
